#!/bin/bash

# sub to bind directories
bindall() {
	mount --bind /proc /mnt/team/proc
	mount --bind /sys /mnt/team/sys
	mount --bind /tmp /mnt/team/tmp
	mount --bind /dev /mnt/team/dev
	mount --bind /dev/pts /mnt/team/dev/pts
}

# sub to unbindall
unbindall() {
	umount /mnt/team/dev/pts
	umount /mnt/team/dev
	umount /mnt/team/tmp
	umount /mnt/team/sys
	umount /mnt/team/proc
}

# format team
mkfs.vfat -v -n EFI /dev/sda1
mkfs.ext4 -v -j -L team /dev/sda2

mount -L team /mnt/team

# create boot/efi if it does not exist
# mount dir
test -d /mnt/team/boot/efi || mkdir -p /mnt/team/boot/efi
mount -L EFI /mnt/team/boot/efi

# mount /mnt/ad64 if not mounted
findmnt /mnt/ad64
test $? -eq 0 || mount /mnt/ad64

# install linux
debootstrap noble /mnt/team http://ubuntu.mirror.ac.za

# edit sources.list
sed -i -e 's/main/main multiverse universe restricted/' /mnt/team/etc/apt/sources.list
# append updates, secrurity, backports, proposed
sed -i -e '$a\deb http://ubuntu.mirror.ac.za noble-updates main multiverse universe restricted\
deb http://ubuntu.mirror.ac.za noble-security main multiverse universe restricted\
deb http://ubuntu.mirror.ac.za noble-proposed main multiverse universe restricted\
deb http://ubuntu.mirror.ac.za noble-backports main multiverse universe restricted' /mnt/team/etc/apt/sources.list

# to setup debhome and svn repository.
# copy debhomepubkey.asc to /etc/apt/keyrings/
# copy debhome.sources to /etc/apt/sources.list.d/
# make directories if necessary
test -d /mnt/team/etc/apt/keyrings || mkdir -p /mnt/team/etc/apt/keyrings
test -d /mnt/team/etc/apt/sources.list.d || mkdir -p /mnt/team/etc/apt/sources.list.d
cp -v /mnt/debhome/debhomepubkey.asc /mnt/team/etc/apt/keyrings/
cp -v /mnt/debhome/debhome.sources /mnt/team/etc/apt/sources.list.d/

# edit fstab
sed -i -e '/LABEL=team/d' /mnt/team/etc/fstab
sed -i -e '/LABEL=ad64/d' /mnt/team/etc/fstab
sed -i -e '$a\LABEL=team / ext4 defaults 0 1' /mnt/team/etc/fstab
sed -i -e '$a\LABEL=ad64 /mnt/ad64 ext4 defaults,noauto 0 2' /mnt/team/etc/fstab

# bind and chroot
bindall

# make user robert
chroot /mnt/team adduser --add-extra-groups --comment "robert key room103 0219596081 0218551556 nothing" robert

# add robert to sudo group
chroot /mnt/team adduser robert sudo

# make directory to mount ad64 in the chroot environment
test -d /mnt/team/mnt/ad64 || mkdir -p /mnt/team/mnt/ad64
# set ownership of ad64
chown robert:robert /mnt/team/mnt

#set links for debhome and svn
chroot /mnt/team ln -s /mnt/ad64/debhome /mnt/debhome
chroot /mnt/team ln -s /mnt/ad64/svn /mnt/svn

# mount ad64 in chroot environment
chroot /mnt/team mount -L ad64
chroot /mnt/team chown robert:robert /mnt/ad64
chroot /mnt/team chown robert:robert -h /mnt/debhome /mnt/svn

# update in the change root environment and upgrade
chroot /mnt/team apt update
chroot /mnt/team apt full-upgrade -y

# install image and essential networking stuff
chroot /mnt/team apt install linux-image-generic linux-headers-generic xz-utils subversion git nano gh rclone coreutils network-manager grub2-common grub-efi-amd64 grub-efi-amd64-signed net-tools iputils-ping openssh-server fdisk mtools ntfs-3g dosfstools parted -y


# install config data for git rclone gh
# and pubkey, sudo robert, debhome.sources
# configdata needs xz-utils
# user robert must exist
# cp -v /mnt/debhome/pool/myown/c/configdata/configdata*.deb /mnt/team/usr/local/bin/
#chroot /mnt/team dpkg -i /usr/local/bin/configdata_1.0.9_amd64.deb
# install confgdata
# dependency is xz-utils
chroot /mnt/team apt install configdata builddebiantree initialise-linux -y

#set root password
chroot /mnt/team passwd

unbindall

# make /boot/grub if it does not exist
test -d /mnt/team/boot/grub || mkdir -p /mnt/team/boot/grub

# create empty /mnt/team/boot/grub/custom.cfg
echo "# custom.cfg" > /mnt/team/boot/grub/custom.cfg

# edit custom.cfg for grub
sed -i -e 'a\set menu_color_normal=white/blue \
set menu_color_highlight=red/light-gray \
set color_normal=yellow/blue \
set color_hightlight=red/black' /mnt/team/boot/grub/custom.cfg

grub-install --root-directory=/mnt/team /dev/sda

bindall
chroot /mnt/team update-grub

# umount ad64
chroot /mnt/team umount /mnt/ad64
unbindall
